spring.application.name=mediconnect-api

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${MEDICONNECT_DB_URL:jdbc:postgresql://localhost:5432/mediconnect}
spring.datasource.username=${MEDICONNECT_DB_USERNAME:postgres}
spring.datasource.password=${MEDICONNECT_DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# JWT
# ===============================
jwt.secret=${MEDICONNECT_JWT_SECRET}
jwt.expiration=86400000

# ===============================
# EMAIL / GMAIL SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MEDICONNECT_MAIL_USERNAME}
spring.mail.password=${MEDICONNECT_MAIL_PASSWORD}

spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate=DEBUG

# ===============================
# NETWORK
# ===============================
java.net.preferIPv4Stack=true